package com.company.taskmanager.api;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.Optional;

/**
 * Represents a draft ToDo item.
 * DraftTodos are generated by the client
 * and passed to the server for tracking and storage
 *
 * Jackson annotations are used to allow for (de)serialization between
 * JSON and java
 */
public class DraftTodo {
    private String name;
    private Optional<String> description;
    private ArrayList<Task> tasks;

    public DraftTodo() {
        // Jackson deserialization
    }

    /**
     * Creates a draftTodo with given name and an optional description.
     * For testing purposes we auto-generate a list of dummy tasks
     * @param name          The name of the draftTodo.
     *                      Ideally short and simple. Spaces are permitted
     * @param description   The description of the draftTodo. As long as necessary.
     */
    public DraftTodo(String name, Optional<String> description) {
        this.name = name;
        this.description = description;
        tasks = new ArrayList<>();
        for (long i=0;i<3;i++) {
            tasks.add(new Task(i, "dummy task "+i, Optional.of("dummy description")));
        }
    }

    @JsonProperty
    public String getName() { return name; }

    @JsonProperty
    public Optional<String> getDescription() { return description; }

    @JsonProperty
    public ArrayList<Task> getTasks() { return tasks; }
}
